/* Standalone GPT generation suite. It intentionally uses the same OpenAI-compatible
 * Chat Completions request shape as the general tester, while keeping its UI and
 * evidence separate from KVV/CCMax server-side suites. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const promptText='生成一个完整、可直接保存为 .html 打开的 HTML 文档，内容是使用 SVG 绘制的鹈鹕骑自行车 2D 动画。动画要有清晰的鹈鹕、车轮、脚踏和连续运动效果，页面打开后即可看到动画。只输出完整 HTML 源码，不要 Markdown 代码围栏，不要解释实现过程，不要调用工具，不要进行测试。';
let aborter=null,modelAborter=null,modelFetchEpoch=0,last=null;
function baseUrl(raw){let u;try{u=new URL(String(raw||'').trim())}catch{throw Error('渠道地址必须是有效的 HTTP / HTTPS URL')}if(!/^https?:$/.test(u.protocol)||u.username||u.password)throw Error('渠道地址仅支持 HTTP(S)，不能包含账号密码');u.pathname=u.pathname.replace(/\/+$/,'');return u.href.replace(/\/+$/,'');}
function endpoint(base,path){const b=baseUrl(base),p=String(path).replace(/^\/+/,'');if(/\/(?:v\d+(?:beta)?|api\/v\d+)$/.test(b))return b+'/'+p;return b+'/v1/'+p;}
function authHeaders(key){return {'Content-Type':'application/json','Authorization':'Bearer '+key};}
function extractText(data){const c=data?.choices?.[0]?.message?.content ?? data?.choices?.[0]?.text ?? data?.output?.[0]?.content ?? data?.output_text ?? '';if(Array.isArray(c))return c.map(x=>typeof x==='string'?x:(x?.text||x?.content||'')).join('');return typeof c==='string'?c:JSON.stringify(c||'');}
function usageOf(data){const u=data?.usage||{};const input=Number.isFinite(Number(u.prompt_tokens))?Number(u.prompt_tokens):Number.isFinite(Number(u.input_tokens))?Number(u.input_tokens):null;const output=Number.isFinite(Number(u.completion_tokens))?Number(u.completion_tokens):Number.isFinite(Number(u.output_tokens))?Number(u.output_tokens):null;const total=Number.isFinite(Number(u.total_tokens))?Number(u.total_tokens):null;const cached=Number.isFinite(Number(u.prompt_tokens_details?.cached_tokens))?Number(u.prompt_tokens_details.cached_tokens):Number.isFinite(Number(u.input_token_details?.cached_tokens))?Number(u.input_token_details.cached_tokens):null;return {input,output,total,cached,consistent:input!=null&&output!=null&&total!=null&&input+output===total,raw:u};}
function assess(source,usage,status){const plain=String(source||'');const clean=plain.replace(/^```(?:html)?\s*/i,'').replace(/\s*```$/,'').trim();const hasHtml=/<(?:!doctype\s+html|html\b|body\b)/i.test(clean),hasSvg=/<svg\b/i.test(clean),hasAnimation=/(<animate\b|requestAnimationFrame|@keyframes|setInterval\s*\(|transition\s*[:(]|transform\s*[:=])/i.test(clean),hasBird=/(pelican|鹈鹕|beak|bill)/i.test(clean),hasBike=/(bicycle|bike|wheel|自行车|车轮)/i.test(clean),hasShapes=/(<circle\b|<path\b|<g\b|<rect\b)/i.test(clean),fence=/^```/i.test(String(source||'')),explanation=/(^|\n)\s*(当然|以下是|下面|说明|实现过程|Here is|Explanation)/i.test(String(source||''));const htmlValid=hasHtml&&hasSvg&&hasShapes;const codeScore=[hasHtml,hasSvg,hasAnimation,hasBird,hasBike,hasShapes].filter(Boolean).length;const generationPass=codeScore>=5&&htmlValid&&!fence&&!explanation;const signals=[];if(!hasHtml)signals.push('未识别完整 HTML 文档结构');if(!hasSvg)signals.push('未识别 SVG');if(!hasAnimation)signals.push('未识别连续动画机制');if(!hasBird)signals.push('未识别鹈鹕元素命名');if(!hasBike)signals.push('未识别自行车/车轮元素');if(fence)signals.push('返回 Markdown 代码围栏');if(explanation)signals.push('混入解释文字');if(status>=400)signals.push('HTTP 请求失败');return {prompt:promptText,html_detected:hasHtml,svg_detected:hasSvg,animation_detected:hasAnimation,pelican_detected:hasBird,bicycle_detected:hasBike,html_valid:htmlValid,code_fence:fence,explanation_detected:explanation,output_length:clean.length,token_usage:{input:usage.input,output:usage.output,total:usage.total,cached:usage.cached,consistent:usage.consistent},signals,code_score:codeScore,generationPass,verdict:generationPass&&usage.consistent?'passed':generationPass||usage.consistent?'inconclusive':'failed',source:clean};}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function value(v){return v==null?'未返回':String(v);}
function renderResult(ev){const g=ev.evaluation,box=$('gptResult');box.hidden=false;const badge=g.verdict==='passed'?'通过':g.verdict==='failed'?'未通过':'待核对';const ok=v=>v?'通过':'未识别';box.innerHTML=`<div class="gpt-result-grid"><div class="gpt-result-item"><b>HTML 文档</b><span class="${g.html_detected?'':'bad'}">${ok(g.html_detected)}</span></div><div class="gpt-result-item"><b>SVG 结构</b><span class="${g.svg_detected?'':'bad'}">${ok(g.svg_detected)}</span></div><div class="gpt-result-item"><b>动画机制</b><span class="${g.animation_detected?'':'bad'}">${ok(g.animation_detected)}</span></div><div class="gpt-result-item"><b>鹈鹕 / 自行车</b><span class="${g.pelican_detected&&g.bicycle_detected?'':'bad'}">${g.pelican_detected&&g.bicycle_detected?'已识别':'需核对'}</span></div><div class="gpt-result-item"><b>输入 tokens</b><span>${value(g.token_usage.input)}</span></div><div class="gpt-result-item"><b>输出 tokens</b><span>${value(g.token_usage.output)}</span></div><div class="gpt-result-item"><b>总 tokens</b><span>${value(g.token_usage.total)}</span></div><div class="gpt-result-item"><b>Token 加总</b><span class="${g.token_usage.consistent?'':'bad'}">${g.token_usage.consistent?'一致':'不一致/缺失'}</span></div><div class="gpt-result-item"><b>综合判定</b><span class="${g.verdict==='failed'?'bad':''}">${badge}</span></div></div><p class="gpt-result-note">可观察信号：源码 ${g.code_score}/6 项特征；${g.signals.length?g.signals.join('；'):'未发现明显降智信号'}。预览仅用于人工查看，不执行任何外部请求。</p>`;const raw=g.source||'';$('gptRaw').textContent=raw;$('gptRawWrap').hidden=!raw;$('gptPreviewWrap').hidden=!g.html_valid;if(g.html_valid){$('gptPreviewWrap').innerHTML='<details open><summary>隔离预览生成的 HTML / SVG 动画</summary><p class="gpt-result-note">运行在 sandbox iframe 中，不会再次调用渠道。</p><iframe sandbox="allow-scripts" referrerpolicy="no-referrer" title="GPT HTML SVG 预览"></iframe></details>';$('gptPreviewWrap').querySelector('iframe').srcdoc=raw;}}
function reportRecord(ev){
  const g=ev.evaluation||{},usage=g.token_usage||{},requests=Array.isArray(ev.requests)?ev.requests:[];
  const requestIds=requests.map((r,i)=>r.id||r.request_id||'gpt-request-'+(i+1));
  const sourceChecks=[['html_detected','完整 HTML 文档'],['svg_detected','SVG 结构'],['animation_detected','连续动画机制'],['pelican_detected','鹈鹕元素命名'],['bicycle_detected','自行车元素命名'],['html_valid','HTML / SVG 源码结构']];
  const checks=sourceChecks.map(([key,title])=>({id:'gpt-'+key,title,status:g[key]===true?'passed':g[key]===false?'inconclusive':'not_covered',dimensions:['protocol'],method:'检查本次模型返回的 HTML / SVG 源码；不执行生成内容或发起额外模型请求。',expected:title+'在源码中有可观察特征。',observed:g[key]===true?'识别到对应源码特征':g[key]===false?'未识别对应源码特征':'未记录',meaning:'源码匹配属于启发式检查；命名缺失不等于画面没有该主体，需在隔离预览中人工核对。',next_step:'结合动画预览核对鹈鹕、自行车、车轮和连续运动的实际效果。',request_ids:requestIds}));
  const usageComplete=[usage.input,usage.output,usage.total].every(v=>v!==null&&v!==undefined&&Number.isFinite(Number(v)));
  checks.push({id:'gpt-usage',title:'输入、输出与总 Token 加总一致性',status:usageComplete?(usage.consistent?'passed':'failed'):'inconclusive',dimensions:['cache'],method:'读取本轮响应 usage，检查 input + output 是否等于 total；不将输入和输出数量相等作为标准。',expected:'完整提供输入、输出和总 Token；总数与输入、输出之和一致。',observed:{input:usage.input,output:usage.output,total:usage.total,cached:usage.cached,consistent:usage.consistent},meaning:usageComplete?'这是上报字段的算术核对，不等同于真实计费审计。':'渠道未返回完整 usage，无法核对算术一致性。',next_step:'按提供方协议核对缓存、推理 token 与 usage 字段口径；差异不能单独证明计费作弊。',request_ids:requestIds});
  checks.push({id:'gpt-output-contract',title:'仅返回源码与请求状态',status:ev.status>=400?'failed':g.code_fence||g.explanation_detected?'failed':'passed',dimensions:['protocol'],method:'核对 HTTP 状态及回复是否混入 Markdown 围栏、解释文字。',expected:'HTTP 成功，仅返回完整 HTML 源码。',observed:{http_status:ev.status,code_fence:g.code_fence,explanation_detected:g.explanation_detected,output_length:g.output_length},meaning:'此项评价本次输出约束遵循情况，不推断模型身份。',next_step:'若输出截断，查看 finish_reason 与输出上限后调整并复测。',request_ids:requestIds});
  return {id:'gpt-'+(ev.fileStamp||Date.now()),kind:'general',source:'general',model:ev.model||'未命名模型',base:ev.base||'',status:g.verdict||'inconclusive',created_at:ev.createdAt?new Date(ev.createdAt).getTime()/1000:Date.now()/1000,duration_ms:Number(ev.duration)||0,prompt:promptText,media:[],result:{config:{base:ev.base||'',model:ev.model||'',prompt:promptText,max_tokens:4000,stream:false},mode:'gpt',checks,requests:requests.map((r,i)=>({...r,id:requestIds[i]})),raw:ev.raw||{},text:g.source||'',gpt_evaluation:g,logs:[{time:ev.createdAt||new Date().toISOString(),message:'GPT 生成专项完成'}]}};
}
async function reportHtml(ev){
  if(!window.WorkbenchReport?.renderExport)throw Error('统一报告模块未加载，请刷新工作台后重试。');
  const record=reportRecord(ev);
  return window.WorkbenchReport.renderExport([record],record.result.logs);
}

async function loadModels(){
 const base=$('gptBase').value.trim(),key=$('gptKey').value.trim();
 if(!base||!key){$('gptModelHint').textContent='请先填写渠道地址和 API Key。';return;}
 window.ModelDiscovery?.showDetails?.($('gptModelHint'),null);
 const epoch=++modelFetchEpoch;
 modelAborter?.abort();modelAborter=new AbortController();
 const button=$('gptModels');button.disabled=true;button.textContent='获取中…';$('gptModelHint').textContent='正在通过工作台代理获取模型列表…';
 try{
  // Hosted workbench pages must use the same-origin discovery proxy as the
  // general/KVV panels. Directly calling the channel here fails on relays that
  // do not expose browser CORS headers (the old GPT path used MediaEngine.listModels).
  if(!window.ModelDiscovery?.list)throw Error('模型发现模块未加载，请刷新工作台后重试。');
  const data=await window.ModelDiscovery.list({base,key,auth:'bearer'},{signal:modelAborter.signal,timeout:30});
  if(epoch!==modelFetchEpoch)return;
  window.ModelDiscovery?.showDetails?.($('gptModelHint'),data);
  const ids=[...new Set((data.models||[]).map(x=>typeof x==='string'?x:x?.id).filter(Boolean))];
  const list=$('gptModelList');list.replaceChildren(...ids.map(id=>{const o=document.createElement('option');o.value=id;return o;}));
  $('gptModelHint').textContent=ids.length?`已获取 ${ids.length} 个模型，可直接选择或手动填写。`:'接口返回 0 个模型，仍可手动填写模型 ID。';
  if(ids.length&&!$('gptModel').value)$('gptModel').value=ids[0];
 }catch(e){
  if(epoch!==modelFetchEpoch)return;
  window.ModelDiscovery?.showDetails?.($('gptModelHint'),e);
  $('gptModelHint').textContent=e.name==='AbortError'?'已取消获取模型列表。':'获取失败：'+(e.message||'未知错误')+'；仍可手动填写模型 ID。';
 }finally{if(epoch===modelFetchEpoch){modelAborter=null;button.disabled=false;button.textContent='获取模型列表 ↓';}}
}
async function run(){if(active())return;const base=$('gptBase').value.trim(),key=$('gptKey').value.trim(),model=$('gptModel').value.trim();if(!base||!key||!model){$('gptMessage').hidden=false;$('gptMessage').className='notice error';$('gptMessage').textContent='请填写渠道地址、API Key 和模型名称。';return;}const timeout=Number(window.gptTimeout||300);aborter=new AbortController();$('gptRun').disabled=true;$('gptStop').disabled=false;$('gptProgress').hidden=false;$('gptProgressText').textContent='请求 GPT 模型并分析 HTML / SVG…';$('gptMessage').hidden=true;$('gptSummary').textContent='正在等待渠道响应…';const started=Date.now();try{const spec=await window.MediaEngine.build({base,key,model,preset:'openai-chat',prompt:promptText,extra:{max_tokens:4000,stream:false}});const result=await window.MediaEngine.request(spec,{timeout,signal:aborter.signal});const data=result.raw||{};const source=result.text||extractText(data),usage=usageOf(data),ev={model,base,status:result.status,raw:data,requests:result.requests||[],createdAt:new Date().toISOString(),fileStamp:(()=>{const d=new Date(),pad=v=>String(v).padStart(2,'0');return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`})(),evaluation:assess(source,usage,result.status),duration:Date.now()-started};if(result.status>=400){ev.evaluation.signals.push('HTTP '+result.status+'：请求失败');ev.evaluation.verdict='failed';}last=ev;renderResult(ev);$('gptSummary').textContent=`已完成：${ev.evaluation.verdict==='passed'?'通过':ev.evaluation.verdict==='failed'?'未通过':'待核对'} · 用时 ${(ev.duration/1000).toFixed(1)} 秒`;$('gptDownload').disabled=false;$('gptDownload').onclick=async()=>{try{const html=await reportHtml(ev),blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`测试报告-${ev.model.replace(/[\\/:*?"<>|]/g,'-')}-${ev.fileStamp}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch(error){$('gptMessage').hidden=false;$('gptMessage').className='notice error';$('gptMessage').textContent='报告生成失败：'+error.message;}};if(window.HistoryCapture&&/^https?:$/.test(location.protocol)){const rec={...reportRecord(ev),client_id:'gpt-'+Date.now()+'-'+Math.random().toString(16).slice(2),title:'GPT 生成专项 · '+model};window.HistoryCapture.record(rec,{key,container:$('gptSummary')});}}catch(e){if(e.name!=='AbortError'){$('gptMessage').hidden=false;$('gptMessage').className='notice error';$('gptMessage').textContent='请求失败：'+e.message;$('gptSummary').textContent='本次专项未完成。';}}finally{aborter=null;$('gptRun').disabled=false;$('gptStop').disabled=true;$('gptProgress').hidden=true;}}
function active(){return !!aborter;}
function activate(){for(const [to,from] of [['gptBase','base'],['gptKey','key'],['gptModel','model']])if($(to)&&!$(to).value&&$(from))$(to).value=$(from).value;$('gptMessage').hidden=true;}
$('gptModels').addEventListener('click',loadModels);$('gptRun').addEventListener('click',run);$('gptStop').addEventListener('click',()=>{if(aborter)aborter.abort();});for(const id of ['gptBase','gptKey'])$(id).addEventListener('input',()=>{modelFetchEpoch++;window.ModelDiscovery?.showDetails?.($('gptModelHint'),null);modelAborter?.abort();modelAborter=null;$('gptModelList').replaceChildren();$('gptModels').disabled=false;$('gptModels').textContent='获取模型列表 ↓';$('gptModelHint').textContent='渠道配置已变化，请重新获取模型列表。';});window.GptSuite={activate};
})();
