'use strict';
// Offline user-flow tests: only source assets and synthetic local API fixtures.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const origin='http://127.0.0.1:8877',token='production-fixture-session';
const errors=[],unexpected=[];let intercepted=0;
const workloadList=['short','long_output','long_context','stream','thinking','vision','tools','cancellation'];
const admission=()=>({status:'retest',label:'待复测 · 证据不足',gates:[{id:'samples',label:'正常业务样本量',status:'inconclusive',observed:12,required:'至少 200 个正常业务任务',detail:'少量样本不能证明长期稳定。'},{id:'business',label:'完整业务任务成功率',status:'passed',observed:'100%',required:'≥99.5%'}],reasons:['样本数量和持续时长尚未满足正式准入要求。'],reliability:{normal_tasks:12,business_successful:12,first_attempt_success_rate:1,eventual_success_rate:1,protocol_success_rate:1,business_success_rate:1,first_content_p95_ms:850,latency_p95_ms:1900,confidence:{method:'Wilson',level:.95,lower_percent:75.75,upper_percent:100,n:12}},validated_envelope:{normal_tasks:12,observation_seconds:110,workloads:{short:{tasks:12,business_successful:12,protocol_success_rate:1,latency_p95_ms:1900}}},cost:{status:'unverified',label:'成本待核算',currency:'CNY',request_count:2,estimated_total:null,actual_total:null,estimated_coverage:{covered:0,total:2},actual_coverage:{covered:0,total:2},production:{actual_cost_per_success:null},rows:[{request_id:'production-1',scope:'production'},{request_id:'production-2',scope:'production'}],comparison:{status:'unverified',detail:'需要同业务配比的实际账单对照。'}}});
const finished=(configuration={})=>({id:'fixture-production',suite:'claude',model:'claude-test',base:'https://relay.example/v1',status:'completed',completed:12,total:12,elapsed:120,history_saved:true,history_id:'history-production',result:{suite:'claude_acceptance',status:'completed',configuration,summary:{passed:12,failed:0},production_validation:{metrics:{task_latency_p95_ms:1900,task_latency_population:'正常逻辑业务任务，包含工具轮次、重试和等待。',retry_attempts:1,tasks_retried:1,recovered_tasks:1,failure_counts:{upstream_5xx:1},time_buckets:[{offset_seconds:0,normal_tasks:12,business_successful:12,business_success_rate:1}]}},admission:admission(),checks:[],transport:{request_count:12}}});
async function fixture(browser,job=null){
 const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 const state={job,posts:[],plans:[],billing:[],calls:[],cancel:0,childJobs:{}};
 await page.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());if(!/^https?:$/.test(url.protocol))return route.continue();intercepted++;
  if(url.origin!==origin){unexpected.push(request.url());return route.abort();}
  if(url.pathname.startsWith('/api/')){
   state.calls.push(url.pathname);const send=value=>route.fulfill({contentType:'application/json',body:JSON.stringify(value)});
   if(url.pathname==='/api/session')return send({token,ready:true,latest:state.job?.id||null,active:state.job?.status==='running'?state.job.id:null,kvv_revision:'offline'});
   assert.equal(request.headers()['x-workbench-token'],token);
   if(url.pathname==='/api/claude/plan'||url.pathname==='/api/acceptance/plan'){const payload=JSON.parse(request.postData());state.plans.push(payload);assert.equal(Object.hasOwn(payload,'key'),false);return send({matrix_only:url.pathname==='/api/acceptance/plan',request_count:payload.production.profile==='off'?12:12+payload.production.max_requests,request_count_is_maximum:true,requests:[],production:{enabled:payload.production.profile!=='off',configuration:payload.production,estimated_tokens:60000,workloads:[{id:'short',label:'短问答',requests_per_task:1,expected:'READY',example:{body:{messages:[{role:'user',content:'Return READY'}]}}}]}});}
   if(url.pathname==='/api/runs'&&request.method()==='POST'){const payload=JSON.parse(request.postData());state.posts.push(payload);state.job={...finished(payload),status:'running',result:null,configuration:payload,completed:0,events:[]};return send({id:state.job.id});}
   if(url.pathname==='/api/runs/fixture-production/cancel'){state.cancel++;state.job={...finished(state.posts.at(-1)||{}),status:'cancelled'};return send({ok:true});}
   if(url.pathname==='/api/runs/fixture-production/cost-template')return send({billing:{rows:[{request_id:'production-1',amount:null,currency:'CNY'},{request_id:'production-2',amount:null,currency:'CNY'}]}});
   if(url.pathname==='/api/runs/fixture-production/billing'){const payload=JSON.parse(request.postData());state.billing.push(payload);const next=admission();next.cost.actual_partial_total=payload.billing.rows.reduce((sum,row)=>sum+row.amount,0);next.cost.actual_total=payload.billing.rows.length===2?next.cost.actual_partial_total:null;next.cost.actual_coverage={covered:payload.billing.rows.length,total:2};next.cost.label='成本证据不完整';state.job.result.admission=next;return send({result:state.job.result,admission:next,history_saved:true,history_id:'history-production'});}
   if(url.pathname==='/api/runs/fixture-production')return send(state.job);
   const childId=url.pathname.match(/^\/api\/runs\/(child-[^/]+)$/)?.[1];if(childId&&state.childJobs[childId])return send(state.childJobs[childId]);
   if(url.pathname==='/api/history')return send({items:[]});
   unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:404,body:'{}'});
  }
  const asset=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));if(!/^[a-z0-9.-]+$/i.test(asset)){unexpected.push(asset);return route.abort();}
  try{await route.fulfill({contentType:({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css'})[path.extname(asset)]||'application/octet-stream',body:await fs.readFile(path.join(__dirname,asset))});}catch{unexpected.push(asset);await route.fulfill({status:404,body:''});}
 });
 await page.goto(origin);await page.waitForFunction(()=>document.getElementById('acceptanceService').textContent.includes('已连接'));
 await page.locator('#legacyBtn').click();await page.locator('[data-suite="claude"]').click();
 return {page,state,close:()=>page.close()};
}
async function openConfig(page){if(!(await page.locator('#claudeProductionSettings').evaluate(n=>n.open)))await page.locator('#claudeProductionSettings>summary').click();}
async function fill(page){await page.locator('#acceptanceBase').fill('https://relay.example/v1');await page.locator('#acceptanceKey').fill('mock-upstream-key');await page.locator('#acceptanceModel').fill('claude-test');}
async function noOverflow(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.production-settings-content').evaluate(n=>['auto','scroll'].includes(getComputedStyle(n).overflowY)),false);}
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{
  {
   const f=await fixture(browser);const {page,state}=f;
   try{
    await fill(page);await openConfig(page);assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'screening');assert.deepEqual(await page.locator('[data-production-workload]:checked').evaluateAll(xs=>xs.map(x=>x.dataset.productionWorkload)),workloadList);
    assert.equal(await page.locator('#claudeProductionContext').inputValue(),'4096');
    await page.locator('#claudeProductionProfile').selectOption('standard');assert.equal(await page.locator('#claudeProductionDuration').inputValue(),'1800');assert.equal(await page.locator('#claudeProductionRequests').inputValue(),'600');assert.equal(await page.locator('#claudeProductionOutput').inputValue(),'4096');
    await page.locator('#claudeProductionPreview').click();await page.locator('#claudePlanDialog').waitFor({state:'visible'});assert.equal(state.plans.at(-1).production.max_requests,600);assert.equal(state.plans.at(-1).pricing.input_per_million,null);assert.equal(state.plans.at(-1).pricing.output_per_million,null);assert.equal(state.plans.at(-1).production.max_estimated_tokens,null);assert.equal(state.plans.at(-1).admission.min_samples,200);assert.match(await page.locator('#claudePlanSummary').innerText(),/追加业务验证.*600.*30 分/s);assert.match(await page.locator('#claudePlanRequests').innerText(),/业务验证请求模板.*短问答/s);assert.equal(state.posts.length,0);await page.locator('#claudePlanClose').click();
    await page.locator('#claudeProductionDuration').fill('90');assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'custom');await page.locator('[data-suite="ccmax"]').click();assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'off');await page.locator('#claudeProductionProfile').selectOption('screening');await page.locator('[data-suite="kimi"]').click();assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'off');await page.locator('[data-suite="claude"]').click();assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'custom');assert.equal(await page.locator('#claudeProductionDuration').inputValue(),'90');
    await page.setViewportSize({width:390,height:900});await noOverflow(page);assert.equal(await page.locator('#claudeProductionDuration').isVisible(),true);
   }finally{await f.close();}
   console.log('PASS: presets, nullable budgets/prices, preview without key or upstream calls, suite draft isolation and mobile layout');
  }
  {
   const f=await fixture(browser);const {page,state}=f;
   try{
    await fill(page);await openConfig(page);await page.locator('.production-custom>summary').click();
    await page.locator('#claudeProductionCases').fill('[{"name":"bad","body":{"Authorization":"credential","messages":[]},"expected_text":"OK"}]');await page.locator('[data-production-workload="custom"]').check();await page.locator('#acceptanceRun').click();assert.match(await page.locator('#acceptanceMessage').innerText(),/凭据/);assert.equal(state.posts.length,0);
    await page.locator('#claudeProductionFile').setInputFiles({name:'business.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{name:'业务断言',body:{model:'old-model',messages:[{role:'user',content:'Read this literal URL https://fixture.example and return READY'}],max_tokens:256},expected_text:'READY'}]))});await page.waitForFunction(()=>document.getElementById('claudeProductionCasesStatus').textContent.includes('已就绪 1'));await page.locator('.production-advanced').last().locator('summary').click();await page.locator('#claudePriceInput').fill('0');await page.locator('#claudePriceOutput').fill('6');await page.locator('#acceptanceRun').click();await page.waitForFunction(()=>document.getElementById('acceptanceStop').disabled===false);assert.equal(state.posts.length,1);assert.equal(state.posts[0].pricing.input_per_million,0);assert.equal(state.posts[0].pricing.cache_read_per_million,null);assert.equal(state.posts[0].production.custom_cases[0].name,'业务断言');assert.equal(Object.hasOwn(state.posts[0].production.custom_cases[0].body,'model'),false);assert.equal(state.posts[0].production.custom_cases[0].expected_text,'READY');assert.equal(await page.locator('#claudeProductionProfile').isDisabled(),true);
    state.job.events=[{suite:'channel_production',type:'progress',completed:4,total:60,logical_tasks:3,elapsed_seconds:40}];await page.waitForFunction(()=>document.getElementById('acceptanceEta').textContent.includes('业务观察：4 / 60'));await page.locator('#acceptanceStop').click();await page.waitForFunction(()=>document.getElementById('acceptanceStop').disabled);assert.equal(state.cancel,1);
   }finally{await f.close();}
   console.log('PASS: credential-free business imports, strict assertions, blank vs zero prices, request budget submission, locked config and cancellation');
  }
  {
   const configuration={request_format:'anthropic',production:{profile:'custom',duration_seconds:240,max_requests:120,concurrency:3,requests_per_minute:0,workloads:['short','custom'],context_tokens:8192,output_tokens:4096,recovery_retries:2,max_estimated_tokens:null,custom_cases:[{title:'已存业务',body:{model:'claude-test',messages:[{role:'user',content:'Return SAVED'}]},expect:{exact_text:'SAVED'}}]},admission:{target_success_rate:99.9,min_samples:500,min_observation_seconds:3600,max_p95_first_content_ms:7000,max_p95_latency_ms:90000,required_workloads:['short','tools']},pricing:{currency:'USD',version:'contract-v2',input_per_million:0,output_per_million:15,cache_read_per_million:null,cache_write_per_million:null}};
   const f=await fixture(browser,finished(configuration));const {page,state}=f;
   try{
    await page.waitForFunction(()=>document.getElementById('claudeProductionRequests').value==='120');assert.equal(await page.locator('#claudeProductionProfile').inputValue(),'custom');assert.equal(await page.locator('#claudePriceInput').inputValue(),'0');assert.equal(await page.locator('#claudePriceCacheRead').inputValue(),'');assert.equal(await page.locator('#claudeAdmissionSamples').inputValue(),'500');assert.equal(await page.locator('#claudeAdmissionPanel').isVisible(),true);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/待复测.*证据不足/s);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/100%/);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/置信区间/);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/P95 完整任务/);await page.getByText('时段稳定性、错误与恢复',{exact:true}).click();assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/上游 5xx.*1 次/);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/实际重试 1 次/);assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/待核算/);assert.equal(state.posts.length,0);
    await openConfig(page);await page.locator('#claudeProductionPreview').click();await page.locator('#claudePlanDialog').waitFor({state:'visible'});assert.equal(state.plans[0].production.custom_cases[0].expected_text,'SAVED');assert.equal(state.plans[0].pricing.currency,'USD');assert.equal(state.plans[0].admission.target_success_rate,99.9);await page.locator('#claudePlanClose').click();
    const pending=page.waitForEvent('download');await page.locator('[data-cost-template]').click();const dl=await pending;assert.match(dl.suggestedFilename(),/^账单模板-claude-test-/);const stream=await dl.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);const template=JSON.parse(Buffer.concat(chunks));assert.equal(template.rows[0].amount,null);
    await page.locator('[data-cost-file]').setInputFiles({name:'ledger.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({rows:[{request_id:'production-1',amount:null,currency:'CNY'},{request_id:'production-2',amount:0,currency:'CNY',authorization:'never-send-this'}]}))});await page.waitForFunction(()=>document.getElementById('acceptanceMessage').textContent.includes('已核对 1 笔'));assert.equal(state.billing.length,1);assert.deepEqual(state.billing[0],{billing:{rows:[{request_id:'production-2',amount:0,currency:'CNY'}]}});assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/0 CNY/);
    await page.locator('[data-cost-file]').setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({rows:[{request_id:'production-1',amount:null,currency:'CNY'}]}))});await page.waitForFunction(()=>document.querySelector('.admission-ledger-status').textContent.includes('空金额不会作为免费提交'));assert.equal(state.billing.length,1);
    await fs.mkdir(path.join(__dirname,'qa-production'),{recursive:true});await page.locator('#claudeAdmissionPanel').screenshot({path:path.join(__dirname,'qa-production/desktop-admission.png')});await page.setViewportSize({width:390,height:900});await noOverflow(page);await page.locator('#claudeAdmissionPanel').screenshot({path:path.join(__dirname,'qa-production/mobile-admission-panel.png')});await page.screenshot({path:path.join(__dirname,'qa-production/mobile-admission.png'),fullPage:true});
   }finally{await f.close();}
   console.log('PASS: nested saved config roundtrip, explicit evidence limits despite 100% samples, confidence metrics, authenticated ledger template/import, unknown billing stays unknown');
  }
  {
   const batch=finished();batch.result={results:[{model:'claude-a',run_id:'child-a',result:finished().result},{model:'claude-b',run_id:'child-b',result:finished().result}]};const f=await fixture(browser,batch);const {page,state}=f;
   try{state.childJobs['child-a']={...finished(),id:'child-a',model:'claude-a'};await page.waitForFunction(()=>document.getElementById('claudeAdmissionPanel').textContent.includes('逐模型准入结论'));assert.equal(await page.locator('#claudeAdmissionPanel button').count(),2);await page.locator('#claudeAdmissionPanel button').first().click();await page.waitForFunction(()=>document.getElementById('acceptanceMessage').textContent.includes('已打开 claude-a'));assert.match(await page.locator('#claudeAdmissionPanel').innerText(),/渠道准入结论/);assert.equal(state.posts.length,0);}finally{await f.close();}
   console.log('PASS: batch models keep separate readiness and billing, drilldown retrieves existing child without new test calls');
  }
  assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);console.log(`PASS: production UI; ${intercepted} intercepted local requests; no upstream calls`);
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
